uvi_web/templates/references.html, uvi_web/templates/search.html, uvi_web/templates/uvi_search.html, uvi_web/templates/welcome_frame.html, uvi_web/uvi_flask.py
1. Clicking logo will take to welcome frame and clicking UVI_search will take to the uvi_search page
2. Created a new page  uvi_search.html instead of just fading on the welcome frame.
=> Navigation bar changes

uvi_web/templates/render_verbnet_top.html
Added a note on subclass frames to say that this is not the full frame. And pointed to the full frame view.
=> Note added in subclass

uvi_web/templates/vn_frame_dynamics.html
Force Dynamics is pointed to the website, not the local resources.
=> Linked FD to the website

uvi_web/templates/class_themroles.html, uvi_web/templates/parent_themroles.html
Mouse-over definitions for thematic roles in the "Roles" section
=> Hovering over roles

uvi_web/templates/render_propbank_predicates.html, uvi_web/templates/render_propbank_rolesets.html
First value in the collapse id open
=> Propbank collapse with first open

uvi_web/templates/render_verbnet_top.html
=> Subclass note changed

corpora/verbnet/appear-48.1.1.xml
Add the appear-48.1,.1.xml file to the UVI
=> add appear-48.1.1.xml file

uvi_web/templates/render_verbnet.html, uvi_web/templates/render_verbnet_parent.html, uvi_web/templates/render_verbnet_top.html
Errors on wordnet underscored words are fixed
=> Wordnet link errors fixed

uvi_web/uvi_flask.py
Changes to show alphabetically sorted list of options in different tabs of "Reference Page"
=> Feat predicate sorting

uvi_web/static/fd_diagrams/pred_calc_for_website_final.json
=> Use the new json file for FD likns

uvi_web/templates/references.html
Add two buttons to the reference page: 1. Force Dynamics. 2. SemLink
=> Add FD and SemLink to reference page

corpora/verbnet/settle-36.1.2.xml
Change Goal at line 216 to Topic
=> Change Goal to Topic

uvi_web/templates/results.html
Changes applied for:
- FrameNet
- OntoNotes
=> Redirect search results to respective resource page

uvi_web/templates/references.html
Add Thematic Role Hierarchy picture to the reference page
=> Add Thematic Role Hierarchy picture

uvi_web/templates/references.html
Add  Preposition Class Hierarchy from https://verbs.colorado.edu/verb-index/vn/preps.txt
=> Add  Preposition Class Hierarchy

uvi_web/templates/applications.html
Links to download VN 3.3, 3.2, 3.1 and Guidelines added on the Download page
=> Links to download old VerbNet versions

uvi_web/templates/resources.html
Add description and Link of Syn-QG project.
=> Add Syn-QG

uvi_web/templates/resources.html
Add Story Realization to Resource page
=> Add Story Realization

uvi_web/build_mongo_collections.py
Fixed database setup error caused locally due to:
- Incorrect db query looking for selrestr_list
- Invalid key "$exists"
=> Fixed local db setup error due to selrestrs and predicates

uvi_web/first_run.ps1, uvi_web/first_run.sh
=> modify first_run.sh

corpora/verbnet/bill-54.5.xml
=> modified verb attributes

uvi_web/run_server.sh
changed the file content, as its there in the server previously
=> updating with the server

uvi_web/static/css/bootstrap_custom.css, uvi_web/templates/results.html, uvi_web/uvi_flask.py
=> Revert "changes for back button"

uvi_web/static/css/bootstrap_custom.css, uvi_web/templates/results.html, uvi_web/uvi_flask.py
=> Revert "Revert "changes for back button""

uvi_web/templates/parent_themroles.html
Resoved Parent-classes roles bug
=> Resolved parent-class roles Bug
